Fix typo in README.md
ShiArthur03/ShiArthur03 pull request #936
Opened 2024-07-11 02:04 UTC by Kenxzk

“像我学习”->“向我学习”

2024-07-11 02:19 UTC, nightt5879 commented
兢兢业业的Typo 警察！！

2024-07-11 02:53 UTC, elin-croft approved these changes

2024-07-11 03:02 UTC, zhimin-z approved these changes

2024-07-11 03:53 UTC, elin-croft commented on README.md
> +到这里，我通过修炼“学术不端”的心法，并通过一定时间的积累，**取得了同龄人五年乃至十年都难以取得的成就**，于是我在29岁就顺利成为国家级人才计划**青年拔尖人才**，是中国有史以来最年轻的青拔！我很骄傲，也很自豪，凭借以上成果，我当选清华能源互联网创新研究院——大容量电力电子与新型电力传输研究中心电力电子仿真研究室主任，先后成功申请到了国家自然科学基金青年基金、中国博士后科学基金，并再次打破
这里加个破折号会不会好一些，于是我在29岁就顺利成为国家级人才计划——**青年拔尖人才**

2024-07-11 04:00 UTC, neverbiasu approved these changes

2024-07-11 04:15 UTC, enpitsuLin approved these changes

2024-07-11 04:36 UTC, tengwang0318 approved these changes

2024-07-11 05:53 UTC, liuup approved these changes

2024-07-11 06:26 UTC, yaoper approved these changes

2024-07-11 06:53 UTC, Caviar011230 approved these changes

2024-07-11 11:22 UTC, nasa1024 approved these changes

2024-07-11 11:44 UTC, childrentime requested changes
一个简单的改动diff这么多，重做！

2024-07-11 11:45 UTC, childrentime requested changes
一个简单的改动diff这么多，重做！

2024-07-12 01:57 UTC, Linchen-Xu approved these changes

2024-07-12 03:01 UTC, crotchets approved these changes

2024-07-14 14:54 UTC, PamlJam commented
Approved.

2024-07-15 07:00 UTC, closed without merging

2024-07-18 14:39 UTC, BUAADreamer commented
approved